### ISSUE TITLE
Organize functions into modules

### ISSUE THREAD

**Issue by ccurtis7** [rahulrzende/uw-cheme599#5]
Great start to your functions. I have a few suggestions on organization.

Move all `.py` files to a sub-directory within your folder. Think of a way you could structure all potential files into modules, groups of code that perform related functions. Think of the way `skimage` is organized: there is a `morphology` module and a `filter` module and a `transform` module. A module is just a `.py` file containing a set of functions.

**Comment by rahulrzende** [comment]
The .py file (module) was moved into an 'src' folder for better organization.

**Comment by rahulrzende** [comment]
Also, an additional test function (just prints hello) has been added to the existing module for testing/previewing purposes.

**Comment by rahulrzende** [comment]
Two modules (one from rahulrzende and other from anjuganju) have been organized into the /src folder now.
