### ISSUE TITLE
Organize developmental Jupyter notebooks.

### ISSUE THREAD

**Issue by ccurtis7** [rahulrzende/uw-cheme599#6]
As you are going to be doing a lot of development, it's good to pro-actively have a strategy for organizing your development notebooks. On each branch, create a sub-directory (with a name like `development` or `notebooks` or something similiar) to store all `.ipynb` files. It's also a good idea to name these with names starting with the date e.g. `04_25_20_preprocessing_functions.ipynb`.

**Comment by akihsirh** [comment]
Created an in_progress folder within the src folder to store .ipynb notebooks that are still in progress. This folder for demonstration purposes has a file that is a work in progress
